#ifndef DISEASE_H
#define DISEASE_H

struct Disease {
	float SPREAD_FACTOR;
	float CARRIER_PROBABILITY;
	float AVERAGE_INCUBATION_DURATION;
	float AVERAGE_TIME_DEATH;
	float AVERAGE_TIME_RECOVERY;
	float DEATH_RATE;
};

#endif //DISEASE_H
